#!/usr/bin/env python
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint
from vyper import v
import vyper
from li_utils.envtools import *

env_setup()

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
args = parser.parse_args()

swagger_client.configuration.api_key['Authorization'] = v.get("api_key")

registry_api = swagger_client.RegistryApi()
registry_api.api_client.host = v.get("api_host")
registry = swagger_client.Registry()

if args.verbose:
    print("Fetching registriess from API host %s..." % (v.get("api_host")))
try:
    api_result = registry_api.get_registries()
    print( "results:" )
    pprint(api_result)
except ApiException as e:
    print("Exception when calling RegistryApi->delete_registry: %s\n" % e)
    sys.exit();

if args.verbose:
    print("Registry fetched successfully.")

