#!/usr/bin/env python
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
from pprint import pprint
import sys
import layint_scan_api
from layint_scan_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

env_setup()

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
args = parser.parse_args()

layint_scan_api.configuration.api_key['Authorization'] = v.get("api_key")

registry_api = layint_scan_api.RegistryApi()
registry_api.api_client.host = v.get("api_host")

if args.verbose:
    print("Fetching registriess from API host %s..." % (v.get("api_host")))
try:
    api_result = registry_api.get_registries()
    print("results:")
    pprint(api_result)
except ApiException as e:
    print("Exception when calling RegistryApi->get_registries: %s\n" % e)
    sys.exit(1)

if args.verbose:
    print("Registry fetched successfully.")
