#!/usr/bin/env python
# Copyright (C) 2018 Layered Insight - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

from __future__ import print_function
import argparse
from pprint import pprint
import sys
import time
import layint_scan_api
from layint_scan_api.rest import ApiException
from vyper import v
from li_utils.envtools import env_setup

# get_image() does work to get image via API
def get_image(imageID):
    if args.verbose:
        print("Checking image scan status on API host %s..." % (v.get("api_host")))
    try:
        api_result = images_api.get_image(imageID)
    except ApiException as e:
        print("Exception when calling ImageApi->get_image: %s\n" % e)
        sys.exit(1)

    if args.verbose:
        pprint(api_result)

    return api_result

# Parse CLI
parser = argparse.ArgumentParser()
parser.add_argument("-v", "--verbose", help="Verbose logging", action="store_true")
parser.add_argument("--imageid", help="ID of image to wait for scan to complete", required=True)
args = parser.parse_args()

env_setup()

layint_scan_api.configuration.api_key['Authorization'] = v.get("api_key")

images_api = layint_scan_api.ImagesApi()
images_api.api_client.host = v.get("api_host")

image = get_image(args.imageid)
i = 0
while image.status != "done" and i < 30:
    if args.verbose:
        print("Waiting 5 seconds before checking again...")
    time.sleep(5)
    image = get_image(args.imageid)
    i = i + 1

if i == 30:
    print("Error timeout reached.")
    sys.exit(1)

if args.verbose:
    print("Image ready.")

sys.exit(0)
